# Phase 1 – Data Profiling
**ShopSphere E-Commerce Analytics – HCL Hackathon**

We first *look* at the raw data before changing anything. Run the cells from top to bottom (Shift + Enter).
This notebook only reads the files – it does not modify them.

## Step 1: Read all the files

In [1]:
import json
import pandas as pd

# dtype=str  -> read everything as text, so nothing is changed by pandas
# keep_default_na=False -> keep blank cells as blank text (do not turn them into NaN)
customers   = pd.read_csv("customers.csv",   dtype=str, keep_default_na=False)
products    = pd.read_csv("products.csv",    dtype=str, keep_default_na=False)
orders      = pd.read_csv("orders.csv",      dtype=str, keep_default_na=False)
order_items = pd.read_csv("order_items.csv", dtype=str, keep_default_na=False)
payments    = pd.read_csv("payments.csv",    dtype=str, keep_default_na=False)
returns     = pd.read_csv("returns.csv",     dtype=str, keep_default_na=False)

# suppliers come as a JSON file
suppliers = pd.DataFrame(json.load(open("suppliers_json.txt")))

In [2]:
customers.head()

,customer_id,first_name,last_name,email,phone,address_line1,city,state,zip_code,country,signup_date,customer_segment,is_active
0,C0143,Chatura,Gokhale,chatura.gokhale143@example.com,06676650618,"H.No. 49, Manda Zila",BANGALORE,Karnataka,919015,India,19-May-2023,Silver,yes
1,C0015,Chaitanya,Sarin,chaitanya.sarin15@example.com,(595) 148-4656,"80, Mangat Road",BANGALORE,Karnataka,823662,India,2021-01-02,Bronze,true
2,C0056,Caleb,Iyengar,caleb.iyengar56@example.com,+91-8740345054,"75, Loke Circle",Mumbai,Maharashtra,N/A,India,08/28/2023,Silverr,yes
3,C0140,Krishna,Baria,krishna.baria140@example.com,4057202590,"818, Sagar Street",Kolkata,West Bengal,798515,India,2022-04-14,Glod,yes
4,C0001,Isaac,Bakshi,isaac.bakshi1@example.com,08196001338,"H.No. 265, Dugal Road",Bangalore,Karnataka,838637,India,2023-03-23,bronze,Y

## Step 2: How big is each table?
`shape` shows (number of rows, number of columns).

In [3]:
print("customers  :", customers.shape)
print("products   :", products.shape)
print("suppliers  :", suppliers.shape)
print("orders     :", orders.shape)
print("order_items:", order_items.shape)
print("payments   :", payments.shape)
print("returns    :", returns.shape)

customers  : (163, 13)
products   : (75, 9)
suppliers  : (19, 6)
orders     : (323, 8)
order_items: (802, 7)
payments   : (329, 6)
returns    : (68, 6)

## Step 3: Look at each table
`head()` shows the first 5 rows.

### 3.1 customers  (CRM system)
- **163 rows, 13 columns** – one row = one customer.
- Columns: customer_id, first_name, last_name, email, phone, address_line1, city, state, zip_code, country, signup_date, customer_segment, is_active.
- All customers are in India. Segments are Bronze / Silver / Gold / Platinum.
- Only **158 unique customer_ids** for 163 rows, so some customers appear more than once.

In [4]:
customers.head()

,customer_id,first_name,last_name,email,phone,address_line1,city,state,zip_code,country,signup_date,customer_segment,is_active
0,C0143,Chatura,Gokhale,chatura.gokhale143@example.com,06676650618,"H.No. 49, Manda Zila",BANGALORE,Karnataka,919015,India,19-May-2023,Silver,yes
1,C0015,Chaitanya,Sarin,chaitanya.sarin15@example.com,(595) 148-4656,"80, Mangat Road",BANGALORE,Karnataka,823662,India,2021-01-02,Bronze,true
2,C0056,Caleb,Iyengar,caleb.iyengar56@example.com,+91-8740345054,"75, Loke Circle",Mumbai,Maharashtra,N/A,India,08/28/2023,Silverr,yes
3,C0140,Krishna,Baria,krishna.baria140@example.com,4057202590,"818, Sagar Street",Kolkata,West Bengal,798515,India,2022-04-14,Glod,yes
4,C0001,Isaac,Bakshi,isaac.bakshi1@example.com,08196001338,"H.No. 265, Dugal Road",Bangalore,Karnataka,838637,India,2023-03-23,bronze,Y

### 3.2 products  (product catalog)
- **75 rows, 9 columns** – one row = one product.
- Columns: product_id, product_name, category, sub_category, unit_price (selling price), cost_price (what it costs us), supplier_id, is_active, launch_date.
- Only **70 unique product_ids** for 75 rows.
- Categories are Electronics, Home & Kitchen, Fashion, Sports and Grocery (written in many different ways).

In [ ]:
products.head()

### 3.3 suppliers  (procurement system, JSON file)
- **19 rows, 6 fields** – one row = one supplier.
- Fields: supplier_id, supplier_name, country, rating, contract_start_date, is_preferred.
- Each product points to its supplier through `supplier_id`.

In [ ]:
suppliers.head()

### 3.4 orders  (e-commerce platform – order header)
- **323 rows, 8 columns** – one row = one order.
- Columns: order_id, customer_id, order_date, order_status, payment_method, channel, promo_code, shipping_city.
- **320 unique order_ids**, placed by **149 different customers**, shipped to 10 cities.
- Channel = where the order was placed (Web / App / Store).

In [ ]:
orders.head()

### 3.5 order_items  (e-commerce platform – order lines)
- **802 rows, 7 columns** – one row = one product line inside an order (an order can have several lines).
- Columns: order_item_id, order_id, product_id, quantity, unit_price, discount_pct, line_total.
- **797 unique order_item_ids**, spread over 329 order_ids.
- `line_total` should be quantity × unit_price after the discount.

In [ ]:
order_items.head()

### 3.6 payments  (payment gateway)
- **329 rows, 6 columns** – one row = one payment transaction.
- Columns: payment_id, order_id, payment_date, amount, payment_status, payment_method.
- **325 unique payment_ids**, covering 320 order_ids.

In [ ]:
payments.head()

### 3.7 returns  (e-commerce platform)
- **68 rows, 6 columns** – one row = one returned order line.
- Columns: return_id, order_item_id, return_date, return_reason, refund_amount, return_status.
- **65 unique return_ids**.

In [ ]:
returns.head()

## How the tables connect
```
customers --(customer_id)--> orders --(order_id)--> order_items --(product_id)--> products --(supplier_id)--> suppliers
                               |                         |
                       (order_id)                 (order_item_id)
                               v                         v
                           payments                  returns
```

## Quick observations from Step 1
- The same label is written in many ways (e.g. `Glod`, `GOLD`, `gold`; `web`, `APP`, `In-store`).
- Dates use different styles (`2024-06-26`, `26-Jun-2024`, `06/09/2025`).
- Some amounts contain currency symbols (`₹210,054.96`, `$181,349.01`).
- Some tables have fewer unique IDs than rows → duplicates.

**Next – Step 4:** check duplicates and missing values.